### ISSUE TITLE
Library behavior changes depending on order of xpath queries

### ISSUE THREAD

**Issue by pmcdonaldgit** [tmittet/microxpath#1]
Thank you for sharing this useful tool.

Can you please clarify - the library appears to require that data be extracted in the same order it appears in the xml. 

Is this by design?

To clarify my question using the example :
`<breakfast_menu>
<food>
<name>Belgian Waffles</name>
<price>$5.95</price>
<description>
Two of our famous Belgian Waffles with plenty of real maple syrup
</description>
<calories>650</calories>
</food>
`
If` I ask for name then price then description everything works fine. If I ask for them in other orders entries are missed or mis reported. 

I would not have a problem with this except that it means that I can not generically look for my tags in an xml file. I must know they are present and in which order before I query.

Any comments?

TIA

**Comment by tmittet** [comment]
I think this issue is solved by commit 9abc431bc5c3cc2f1f53454399c3c7332bed00d2
