### ISSUE TITLE
Data size

### ISSUE THREAD

**Issue by magnus-goransson-altitude365-com** [tmittet/microxpath#3]
First of all, thanks for a great job!

Secondly, i had problems reading large data chunks from an XML-source. If i had more than 255 chars to return from the xml the result got broken. In my case it was when i changed the Sonos upnp library to also extract the DIDL from Sonos. I just changed the position and matchCount variabled from uint8_t to uint16_t type and the problem was solved.

`  private:
    PGM_P *path;
    size_t pathSize;
    #ifndef XML_PICO_MODE
    uint8_t tagChecksum;
    uint8_t checksum;
    #endif
    uint8_t level;
    uint16_t position;
    uint16_t matchCount;
    uint8_t matchLevel;`

Maybe that is something to change in the source code?

Thanks,

Magnus

**Comment by tmittet** [comment]
That is a really good idea. I thought 255 bytes of memory would be enough for anybody :)
