### ISSUE TITLE
Extend include to support ESP8266

### ISSUE THREAD

**Issue by mguntli** [tmittet/microxpath#4]
Hi Thomas

Thank you for your library!
How about extending the headers to support as well the ESP8266?
    
    #if (defined(__AVR__))
        #include <avr/pgmspace.h>
    #else
        #include <pgmspace.h>
    #endif

See commit https://github.com/tmittet/microxpath/commit/0f76440e94f9f502ca5546e93b26a71496f5d980

**Comment by tmittet** [comment]
Good idea sir! Let me know if it works :)

**Comment by tmittet** [comment]
I see the world has moved on while I've been away :) I just ordered my first NodeMCU and WeMos D1. Do you have any tips to get started or is it plug and play?

**Comment by mguntli** [comment]
Basically just download the ESP8266 board package and it just works out of the box.
You can follow this guide: https://github.com/esp8266/Arduino/#installing-with-boards-manager

FYI, since the chip has 80kB of RAM I have taken another attempt and the strings are now created and processed with std::string (it's just much easier to create those huge SOAP-XML requests).
The library is currently under development and a port of of the existing Java library to ESP8266 (I know it's highly inefficient with all those strings, but the code readability and ability to merge features with the Java library is quite good).

ESP8266 Sonos library:
https://github.com/soreco-project/soreco-firmware/blob/feature/sonos/src/Sonos/SonosDevice.cpp#L41

Java Sonos library:
https://github.com/vmichalak/sonos-controller/blob/master/src/main/java/com/vmichalak/sonoscontroller/SonosDevice.java#L26

**Comment by tmittet** [comment]
It's much better to use std:string. The ATMega328p MCU, that I wrote the Sonos and MicroXPath libraries for, only has 2kB RAM and you usually end up with less than 1kB when the program has loaded. If I remember correctly, I estimated that MicroXPath would use no more than 16 bytes of RAM :)

The project I'm working on right now is simply about turning on my amp when the Sonos Connect is playing and turning it back of after a few minutes of inactivity. My amp has an RS232 interface, so I'll stick with the ATMega chip for this project.

The soreco project you are working on seem really cool! Let me know if you have any questions or if I can help out. This device would be really useful for some of my projects.

Have you considered adding an IR receiver, an IR transmitter and a RS232 port?

I'm not sure what you are planning to do, but adding this should not make it much more expensive. You could hook the hardware serial on the ESP8266 up to a RJ11 connector through a MAX3232. The IR receiver requires an input with interrupt capability and the IR transmitter diode needs a pin with PWM capability at ~38KHz. The reason I'm asking is that this would allow people to interface with RS232 capable devices like amps, projectors, lighting control systems, etc using a RJ11 to DB9 cables. And it would allow receiving IR command and control devices using IR.

**Comment by tmittet** [comment]
Thinking about it for a few seconds: It would be better to simply add a couple of multi purpose mini jacks for the IR receiver and IR transmitter.

**Comment by mguntli** [comment]
I like the idea of additional IR!
The current hardware is supposed to be IP67 waterproof (up to 0.5m), so you can use it in your bathroom as well. How about extension hardware with BLE / native 2.4GHz low power interfaces?

The goal of soreco is quite simple at the beginning: it can do exactly one thing (Control your Sonos speaker) - and this rather well.

**Comment by tmittet** [comment]
I misunderstood your project a bit (probably wishful thinking since it fits better with what I'm doing :). I somehow thought that the Android app would work as a controller and that the firmware piece would work as a hub somehow, but that doesn't make sense since Sonos has an app already :)
Making a simple remote for the Sonos system makes much more sense.You are probably better of sticking with your original idea. Keep it simple!
